### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertText' of undefined

### ISSUE THREAD

**Issue by mattwilkerson1121** [avocode/avocode-atom-integration#3]
1. Open Avocode App inside Atom 
2. Click Layer in Avocode App Pane
3. CMD+SHIFT+V to copy layer styles to css

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [avocode](https://github.com/avocode/avocode-atom-integration) package 0.0.8

### Stack Trace

Uncaught TypeError: Cannot read property 'insertText' of undefined

```
At /Users/mwilker/.atom/packages/avocode/lib/avocode.js:61

TypeError: Cannot read property 'insertText' of undefined
    at Object.pasteSelectedStyle (/packages/avocode/lib/avocode.js:61:13)
    at HTMLElement.avocodePasteStyle (/packages/avocode/lib/avocode.js:24:43)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -3:20 avocode:split-right (input.hidden-input)
  2x -0:39.6.0 avocode:paste-style (webview.)
```

### Non-Core Packages

```
atom-nodejs-snippets 2.0.0 
atom-vuex 0.5.0 
atom-xcode 0.1.3 
avocode 0.0.8 
code-peek 1.4.21 
js2coffee 0.19.1 
language-vue 0.23.1 
language-vue-component 0.5.0 
vue-autocompile 0.0.6 
vue-autocomplete 0.1.1 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs-snippets 0.1.0 
vuejs2-snippets 0.15.0 
```

**Comment by petrbrzek** [comment]
@mattwilkerson1121 Thanks for reporting this. I've fixed in 0.0.9 version.
